name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create tsconfig for electron
        run: |
          echo '{
            "compilerOptions": {
              "target": "ES2021",
              "module": "commonjs",
              "lib": ["dom", "es2021"],
              "declaration": true,
              "declarationMap": true,
              "sourceMap": true,
              "outDir": "./dist/electron",
              "rootDir": "./",
              "strict": true,
              "allowJs": true,
              "esModuleInterop": true,
              "skipLibCheck": true,
              "forceConsistentCasingInFileNames": true,
              "moduleResolution": "node",
              "resolveJsonModule": true,
              "baseUrl": "./",
              "paths": {
                "@shared/*": ["shared/*"],
                "@electron/*": ["electron/*"]
              }
            },
            "include": [
              "electron/**/*",
              "shared/**/*"
            ],
            "exclude": [
              "node_modules",
              "dist"
            ]
          }' > electron/tsconfig.json

      - name: Build Electron
        run: npm run build:electron

      - name: Build React
        run: npm run build

      - name: Build App
        run: npm run electron:build
