name: Build Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Clean install dependencies
      run: |
        npm install
      shell: bash
      
    - name: Install TypeScript
      run: npm install -g typescript
      
    - name: Build TypeScript
      run: tsc -p electron/tsconfig.json
        
    - name: Build React app
      run: npm run build
      env:
        CI: false
      
    - name: Build Electron app
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          npm run electron:build:win
        else
          npm run electron:build:mac
        fi
      shell: bash
      env:
        CI: false
      
    - name: Upload Windows artifacts
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: dist/*.exe
        
    - name: Upload macOS artifacts
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: |
          dist/*.dmg
          dist/mac-universal/*.dmg
