name: Build Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Clean install and update package-lock.json
      run: |
        rm -f package-lock.json
        npm install
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add package-lock.json
        git commit -m "Update package-lock.json" || echo "No changes to commit"
        git push origin HEAD:${{ github.ref }}
      
    - name: Build React app
      run: npm run build
      
    - name: Build Electron app
      run: npm run electron:build
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: dist/*.exe
